name: a_new_day
description: "Ứng dụng theo dõi thói quen, cảm xúc và nhật ký hắng ngày"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  drift: ^2.13.0
  sqlite3_flutter_libs: any
  path_provider: ^2.0.14
  path: ^1.9.0
  provider: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  flutter_speed_dial: ^7.0.0
  fl_chart: ^1.0.0
  image_picker: ^1.0.0
  flutter_image_compress: ^2.1.0
  image: ^4.0.17
  numberpicker: ^2.1.1
  lottie: ^2.6.0
  table_calendar: ^3.0.8
  url_launcher: ^6.2.5
  flutter_riverpod: ^2.6.1

  page_flip: ^0.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.13.0
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/emoji_default/
    - assets/sticker/

  fonts:
    - family: PlaywriteVNGuides
      fonts:
        - asset: assets/fonts/PlaywriteVNGuides-Regular.ttf
    - family: DFVN
      fonts:
        - asset: assets/fonts/DFVN-Excalifont.ttf
